### ISSUE TITLE
Mongo DB Filter

### ISSUE THREAD

**Issue by VerasThiago** [VerasThiago/plataforma-apc#9]
Find a way to query like sql. Example of MongoDB website not working

`db.inventory.find( { status: "A" }, { item: 1, status: 1, _id: 0 } )` Mongo
`SELECT item, status from inventory WHERE status = "A"` SQL

**Comment by vitordullens** [comment]
In MongoCompass you have to use the "PROJECT"  section on filter, like:
FILTER : `{ status: "A" }`
PROJECT: `{ item: 1, status: 1, _id: 0 }`

In the MongoShell itself you have to use the query:
`db.MyCollection.find( { status: "A" }, { item: 1, status: 1, _id: 0 } )`

**Comment by VerasThiago** [comment]
The solution proposed by @vitordullens was correct, but the main point was how to implement this in Go, the answer was found [here](https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/) in Go section.

I was very close to solve this problem, because when you make a query in MongoDB, you can use a filter to restrict the documents. To show some specific data you need to specify the project (what you want to project). I was trying to find how to add this project into the query, here's the answer :

Add the project in the third parameter of the query function.

```
filter := bson.D{
	{"matricula", student.Matricula},
	{"password", student.Password},
}
projection := bson.D{
	{"password", 0},
}

if err := collection.FindOne(
	context.TODO(),
	filter,
	options.FindOne().SetProjection(projection),  // Solution here!
).Decode(&findStudent); err != nil {
	return findStudent, err
}
```
